version: 2

sources:
    - name: staging
      database: wise-invention-413814
      schema: streamify_stg
      tables:
        - name: listen_events
        - name: page_view_events
        - name: auth_events
        - name: songs
        - name: state_codes